---
- name: Build Topology
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox

  vars:
    install_state: present

  tasks:
    - name: Load API variables
      include_vars:
        file: vars/api.yml
        name: api
    - name: Load Topology File
      include_vars:
        file: topologies/evpn.yml
        name: topology

    # Site Info
    - name: Setup Regions
      netbox_region:
        netbox_url: "{{ api.url }}"
        netbox_token: "{{ api.token }}"
        data: "{{ item }}"
        state: "{{ install_state }}"
      loop: "{{ topology.netbox.regions }}"
      loop_control:
        loop_var: item
        label: "{{ item['name'] }}"
    
    - name: Setup Sites
      netbox_site:
        netbox_url: "{{ api.url }}"
        netbox_token: "{{ api.token }}"
        data: "{{ item }}"
        state: "{{ install_state }}"
      loop: "{{ topology.netbox.sites }}"
      loop_control:
        loop_var: item
        label: "{{ item['name'] }}"

    # Rack Info
    # - name: Setup Rack Groups
    #   netbox_rack_group:
    #     netbox_url: "{{ api.url }}"
    #     netbox_token: "{{ api.token }}"
    #     data: "{{ item }}"
    #     state: "{{ install_state }}"
    #   loop: "{{ topology.netbox.rack_groups }}"
    #   loop_control:
    #     loop_var: item
    #     label: "{{ item['name'] }}"

    # - name: Setup Racks
    #   netbox_rack:
    #     netbox_url: "{{ api.url }}"
    #     netbox_token: "{{ api.token }}"
    #     data: "{{ item }}"
    #     state: "{{ install_state }}"
    #   loop: "{{ topology.netbox.racks }}"
    #   loop_control:
    #     loop_var: item
    #     label: "{{ item['name'] }}"

    # Device Info
    - name: Setup Device Roles
      netbox_device_role:
        netbox_url: "{{ api.url }}"
        netbox_token: "{{ api.token }}"
        data: "{{ item }}"
        state: present
      loop: "{{ topology.netbox.device_roles }}"
      loop_control:
        loop_var: item
        label: "{{ item['name'] }}"

    - name: Load Devices
      netbox_device:
        netbox_url: "{{ api.url }}"
        netbox_token: "{{ api.token }}"
        data: "{{ item }}"
        state: "{{ install_state }}"
      loop: "{{ topology.netbox.devices }}"
      loop_control:
        loop_var: item
        label: "{{ item['name'] }}"

    # IPAM Info
    - name: Load IPAM Roles
      netbox_ipam_role:
        netbox_url: "{{ api.url }}"
        netbox_token: "{{ api.token }}"
        data: "{{ item }}"
        state: "{{ install_state }}"
      loop: "{{ topology.netbox.ipam_roles }}"
      loop_control:
        loop_var: item
        label: "{{ item['name'] }}"

